# Generated by Django 4.1.13 on 2024-02-25 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_tweet_agreements_tweet_disagreements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='agreements',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='disagreements',
        ),
        migrations.AddField(
            model_name='tweet',
            name='agreements',
            field=models.ManyToManyField(blank=True, related_name='agreed_tweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tweet',
            name='disagreements',
            field=models.ManyToManyField(blank=True, related_name='disagreed_tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
